# Copyright (c) 2026 Joseph Verdicchio and EvidenceOS Contributors
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "stable"
profile = "minimal"
components = ["rustfmt", "clippy", "llvm-tools-preview"]
