apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evidenceos.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "evidenceos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  trusted_oracle_keys.json: |
{{ .Values.config.trustedOracleKeysJson | indent 4 }}
