{{- if and .Values.mtls.enabled (not .Values.mtls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evidenceos.fullname" . }}-mtls
  labels:
    app.kubernetes.io/name: {{ include "evidenceos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.mtls.certFile }}: ""
  {{ .Values.mtls.keyFile }}: ""
  {{ .Values.mtls.caFile }}: ""
---
{{- end }}
{{- if and (eq .Values.signingKeys.provider "file") (not .Values.signingKeys.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evidenceos.fullname" . }}-signing-key
  labels:
    app.kubernetes.io/name: {{ include "evidenceos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.signingKeys.keyFileName }}: ""
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evidenceos.fullname" . }}-preflight
  labels:
    app.kubernetes.io/name: {{ include "evidenceos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  token: {{ .Values.daemon.preflightBearerToken | quote }}
